const express = require('express');
const cors    = require('cors');
const fetch   = require('node-fetch');

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static('public'));

// ─── Hardcoded credentials ────────────────────────────────────────────────────
const VEEQO_KEY = 'Vqt/dc075e1b329ee377fef82c5faa2f96d7';
const QB_TOKEN  = 'b4avcr_mcrg_0_v6hayncag6syty4u5bxmtzmvh';
const QB_REALM  = 'carlgarcia.quickbase.com';
const QB_TABLE  = 'bvgseawft';
const COMPANY_IDS = { Amazon:2709, eBay:2710, Shopify:2831, Walmart:3951, Etsy:3966 };

// ─── Helpers ──────────────────────────────────────────────────────────────────
function detectChannel(order) {
  const ch = ((order.channel?.name || '') + (order.channel_type || '')).toLowerCase();
  if (ch.includes('amazon'))  return 'Amazon';
  if (ch.includes('ebay'))    return 'eBay';
  if (ch.includes('walmart')) return 'Walmart';
  if (ch.includes('shopify')) return 'Shopify';
  if (ch.includes('etsy'))    return 'Etsy';
  return order.channel?.name || 'Other';
}

function isGreenTagged(order) {
  return (order.tags || []).some(t =>
    t.colour === '#99cc00' || (t.name || '').toLowerCase().includes('quickbase')
  );
}

function getOrderId(order) {
  return order.channel_order_id || order.number || String(order.id);
}

function fmtDate(s) {
  if (!s) return '';
  try { return new Date(s).toISOString().slice(0, 10); }
  catch { return String(s).slice(0, 10); }
}

function fmtDateDisplay(s) {
  if (!s) return '';
  try {
    const d = new Date(s);
    return `${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}/${d.getFullYear()}`;
  } catch { return String(s).slice(0, 10); }
}

function buildNotes(channel, orderId, customer, dateRaw, lineItems, total) {
  const lines = [
    `Order ID: ${orderId}`,
    `Channel: ${channel}`,
    `Order Date: ${fmtDateDisplay(dateRaw)}`,
    `Customer: ${customer}`,
    '',
    '--- Line Items ---',
  ];
  for (const li of lineItems) {
    lines.push(`Item: ${li.title}`);
    lines.push(`SKU: ${li.sku}   Qty: ${li.qty}   Price: $${Number(li.price).toFixed(2)}`);
  }
  lines.push('', `Order Total: $${Number(total).toFixed(2)}`);
  return lines.join('\n');
}

function generateEbayHTML(orderId, customer, dateRaw, lineItems, total) {
  const rows = lineItems.map(li =>
    `<tr><td>${li.title}</td><td>${li.sku}</td><td style="text-align:center">${li.qty}</td><td style="text-align:right">$${Number(li.price).toFixed(2)}</td></tr>`
  ).join('');
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>eBay Order ${orderId}</title>
<style>body{font-family:Arial,sans-serif;max-width:720px;margin:40px auto;padding:20px;color:#333}
h1{color:#e53238;border-bottom:2px solid #e53238;padding-bottom:10px}
.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;background:#f9f9f9;padding:15px;border-radius:6px;margin:15px 0}
.meta-row label{font-size:11px;color:#666;text-transform:uppercase;display:block}
.meta-row span{font-weight:bold;font-size:14px}
table{width:100%;border-collapse:collapse;margin:15px 0}
th{background:#e53238;color:#fff;padding:8px 12px;text-align:left;font-size:12px}
td{padding:8px 12px;border-bottom:1px solid #eee;font-size:13px}
.total-row td{font-weight:bold;background:#f0f0f0}
.footer{font-size:11px;color:#999;margin-top:20px;border-top:1px solid #eee;padding-top:10px}
</style></head><body>
<h1>eBay Order Details</h1>
<div class="meta">
  <div class="meta-row"><label>Order ID</label><span>${orderId}</span></div>
  <div class="meta-row"><label>Order Date</label><span>${fmtDateDisplay(dateRaw)}</span></div>
  <div class="meta-row"><label>Customer</label><span>${customer}</span></div>
  <div class="meta-row"><label>Channel</label><span>eBay</span></div>
</div>
<table>
  <thead><tr><th>Item</th><th>SKU</th><th style="text-align:center">Qty</th><th style="text-align:right">Price</th></tr></thead>
  <tbody>${rows}
  <tr class="total-row"><td colspan="3">Order Total</td><td style="text-align:right">$${Number(total).toFixed(2)}</td></tr>
  </tbody>
</table>
<div class="footer">Generated by eCommerce → QuickBase Sync &nbsp;·&nbsp; ${new Date().toLocaleString()}</div>
</body></html>`;
}

// ─── MAIN SYNC — Server-Sent Events ──────────────────────────────────────────
app.get('/api/sync/run', async (req, res) => {
  const attachField = req.query.attachField || '';

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();

  const send = (type, data) =>
    res.write(`data: ${JSON.stringify({ type, ...data })}\n\n`);

  send('log', { msg: '🚀 Starting Veeqo → QuickBase sync…' });

  try {
    // ── 1. Fetch all awaiting-fulfillment orders from Veeqo ──────────────────
    send('log', { msg: '📦 Fetching orders from Veeqo…' });
    const allOrders = [];
    for (let page = 1; page <= 10; page++) {
      const r = await fetch(
        `https://api.veeqo.com/orders?status=awaiting_fulfillment&page_size=50&page=${page}`,
        { headers: { 'x-api-key': VEEQO_KEY } }
      );
      if (!r.ok) { send('log', { msg: `❌ Veeqo HTTP ${r.status}` }); break; }
      const batch = await r.json();
      if (!Array.isArray(batch) || !batch.length) break;
      allOrders.push(...batch);
      if (batch.length < 50) break;
    }
    send('log', { msg: `📦 Fetched ${allOrders.length} awaiting-fulfillment orders` });

    // ── 2. Filter: skip already-green ────────────────────────────────────────
    const toProcess = allOrders.filter(o => !isGreenTagged(o));
    const skipped   = allOrders.length - toProcess.length;
    send('log', { msg: `⏭️  Skipping ${skipped} already-synced (green-tagged) orders` });
    send('log', { msg: `📋 ${toProcess.length} new orders to push` });
    send('progress', { total: toProcess.length, done: 0 });

    if (!toProcess.length) {
      send('log', { msg: '✅ Everything is up to date — nothing to push!' });
      send('done', { pushed:0, failed:0, tagFailed:0, skipped, channelCounts:{} });
      return res.end();
    }

    let pushed = 0, failCount = 0, tagFailed = 0;
    const channelCounts = {};

    for (let i = 0; i < toProcess.length; i++) {
      const raw     = toProcess[i];
      const channel = detectChannel(raw);
      const orderId = getOrderId(raw);
      const addr    = raw.deliver_to || {};
      const customer = [addr.first_name, addr.last_name].filter(Boolean).join(' ') || '—';
      const dateRaw  = raw.created_at || '';
      const lineItems = (raw.line_items || []).map(li => ({
        sku:   li.sellable?.sku_code || li.sku || '?',
        title: li.sellable?.title    || li.product_title || 'Unknown',
        qty:   li.quantity || 1,
        price: parseFloat(li.price || 0),
      }));
      const total = parseFloat(raw.total_price || 0);
      const notes = buildNotes(channel, orderId, customer, dateRaw, lineItems, total);

      const record = {
        '6':  { value: fmtDate(dateRaw) },
        '35': { value: orderId },
        '50': { value: notes },
        '52': { value: 'Open' },
      };
      const cid = COMPANY_IDS[channel];
      if (cid) record['74'] = { value: cid };

      try {
        // ── Push to QB ───────────────────────────────────────────────────────
        const qbR = await fetch('https://api.quickbase.com/v1/records', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `QB-USER-TOKEN ${QB_TOKEN}`,
            'QB-Realm-Hostname': QB_REALM,
            'User-Agent': 'veeqo-sync/4.0',
          },
          body: JSON.stringify({ to: QB_TABLE, data: [record] }),
        });
        const qbData = await qbR.json();
        const recId  = qbData.metadata?.createdRecordIds?.[0]
                    || qbData.metadata?.updatedRecordIds?.[0];

        if (!recId) throw new Error(JSON.stringify(qbData).slice(0, 200));

        send('log', { msg: `  ✅ [${channel}] ${orderId}  →  QB #${recId}` });
        pushed++;
        channelCounts[channel] = (channelCounts[channel] || 0) + 1;

        // ── eBay HTML attachment ─────────────────────────────────────────────
        if (channel === 'eBay' && attachField) {
          try {
            const html = generateEbayHTML(orderId, customer, dateRaw, lineItems, total);
            const ar   = await fetch(
              `https://api.quickbase.com/v1/files/${QB_TABLE}/${recId}/${attachField}/0`,
              {
                method: 'POST',
                headers: {
                  'Authorization': `QB-USER-TOKEN ${QB_TOKEN}`,
                  'QB-Realm-Hostname': QB_REALM,
                  'Content-Type': 'application/octet-stream',
                  'Content-Disposition': `inline; filename="ebay-order-${orderId}.html"`,
                },
                body: Buffer.from(html, 'utf8'),
              }
            );
            send('log', { msg: ar.ok
              ? `     📎 eBay order detail attached to QB`
              : `     ⚠️  Attachment failed (${ar.status})` });
          } catch (ae) {
            send('log', { msg: `     ⚠️  Attachment error: ${ae.message}` });
          }
        }

        // ── Apply green tag in Veeqo ─────────────────────────────────────────
        // Use tag_list with TAG NAMES (strings), preserving existing tags
        try {
          const existingNames = (raw.tags || [])
            .map(t => t.name)
            .filter(n => n && n.toLowerCase() !== 'entered into quickbase');
          const tagList = [...existingNames, 'Entered into Quickbase'];

          const tr = await fetch(`https://api.veeqo.com/orders/${raw.id}`, {
            method: 'PUT',
            headers: {
              'x-api-key': VEEQO_KEY,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ order: { tag_list: tagList } }),
          });

          if (tr.ok) {
            send('log', { msg: `     🟢 Tagged "Entered into Quickbase" in Veeqo` });
          } else {
            const errText = await tr.text();
            send('log', { msg: `     ⚠️  Tag failed (${tr.status}): ${errText.slice(0, 100)}` });
            tagFailed++;
          }
        } catch (te) {
          send('log', { msg: `     ⚠️  Tag error: ${te.message}` });
          tagFailed++;
        }

      } catch (e) {
        send('log', { msg: `  ❌ [${channel}] ${orderId}: ${e.message.slice(0, 120)}` });
        failCount++;
      }

      send('progress', { total: toProcess.length, done: i + 1 });
    }

    // ── Summary ──────────────────────────────────────────────────────────────
    send('log', { msg: '' });
    send('log', { msg: `═══════════════════════════════════════` });
    send('log', { msg: `✅ Sync complete — ${pushed} pushed, ${failCount} failed, ${skipped} already done` });
    if (tagFailed > 0)
      send('log', { msg: `⚠️  ${tagFailed} orders couldn't be tagged green — check Veeqo API permissions` });
    for (const [ch, n] of Object.entries(channelCounts))
      send('log', { msg: `   ${ch}: ${n}` });
    send('done', { pushed, failed:failCount, tagFailed, skipped, channelCounts });

  } catch (e) {
    send('error', { msg: `Fatal sync error: ${e.message}` });
  }

  res.end();
});

// ─── Veeqo Tag (standalone) ───────────────────────────────────────────────────
app.post('/api/veeqo/tag/:orderId', async (req, res) => {
  try {
    const { orderId }      = req.params;
    const { existingTags = [] } = req.body;
    const tagList = [...new Set([...existingTags.filter(n =>
      n && n.toLowerCase() !== 'entered into quickbase'
    ), 'Entered into Quickbase'])];

    const r = await fetch(`https://api.veeqo.com/orders/${orderId}`, {
      method: 'PUT',
      headers: { 'x-api-key': VEEQO_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ order: { tag_list: tagList } }),
    });
    const data = await r.json();
    res.status(r.status).json(data);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ─── Veeqo Orders proxy ───────────────────────────────────────────────────────
app.get('/api/veeqo/orders', async (req, res) => {
  try {
    const { status, page_size = 50, page = 1 } = req.query;
    const apiKey = req.headers['x-veeqo-key'] || VEEQO_KEY;
    let url = `https://api.veeqo.com/orders?page_size=${page_size}&page=${page}`;
    if (status && status !== 'all') url += `&status=${status}`;
    const r = await fetch(url, { headers: { 'x-api-key': apiKey } });
    res.status(r.status).json(await r.json());
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ─── eBay Orders proxy ────────────────────────────────────────────────────────
app.get('/api/ebay/orders', async (req, res) => {
  try {
    const { limit=50, offset=0, filter } = req.query;
    const token = req.headers['x-ebay-token'];
    if (!token) return res.status(400).json({ error: 'Missing eBay token' });
    let url = `https://api.ebay.com/sell/fulfillment/v1/order?limit=${limit}&offset=${offset}`;
    if (filter) url += `&filter=${encodeURIComponent(filter)}`;
    const r = await fetch(url, {
      headers: { Authorization:`Bearer ${token}`, 'Content-Type':'application/json' }
    });
    res.status(r.status).json(await r.json());
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ─── eBay Transactions proxy ──────────────────────────────────────────────────
app.get('/api/ebay/transactions', async (req, res) => {
  try {
    const { limit=200, offset=0, filterDate } = req.query;
    const token = req.headers['x-ebay-token'];
    if (!token) return res.status(400).json({ error: 'Missing eBay token' });
    let url = `https://api.ebay.com/sell/finances/v1/transaction?limit=${limit}&offset=${offset}&transactionType=SALE`;
    if (filterDate) url += `&filter=${encodeURIComponent(filterDate)}`;
    const r = await fetch(url, {
      headers: {
        Authorization:`Bearer ${token}`,
        'Content-Type':'application/json',
        'X-EBAY-C-MARKETPLACE-ID':'EBAY_US',
      }
    });
    res.status(r.status).json(await r.json());
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ─── QuickBase Records proxy ──────────────────────────────────────────────────
app.post('/api/quickbase/records', async (req, res) => {
  try {
    const qbToken = req.headers['x-qb-token'] || QB_TOKEN;
    const qbRealm = req.headers['x-qb-realm'] || QB_REALM;
    const r = await fetch('https://api.quickbase.com/v1/records', {
      method: 'POST',
      headers: {
        'QB-Realm-Hostname': qbRealm,
        Authorization: `QB-USER-TOKEN ${qbToken}`,
        'Content-Type': 'application/json',
        'User-Agent': 'veeqo-sync/4.0',
      },
      body: JSON.stringify(req.body),
    });
    const text = await r.text();
    try { res.status(r.status).json(JSON.parse(text)); }
    catch { res.status(r.status).json({ raw: text }); }
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ─── QuickBase File Attachment proxy ─────────────────────────────────────────
app.post('/api/quickbase/attach/:tableId/:recordId/:fieldId', async (req, res) => {
  try {
    const { tableId, recordId, fieldId } = req.params;
    const { filename, content } = req.body; // content = base64 string
    const buf = Buffer.from(content, 'base64');
    const r = await fetch(
      `https://api.quickbase.com/v1/files/${tableId}/${recordId}/${fieldId}/0`,
      {
        method: 'POST',
        headers: {
          Authorization: `QB-USER-TOKEN ${QB_TOKEN}`,
          'QB-Realm-Hostname': QB_REALM,
          'Content-Type': 'application/octet-stream',
          'Content-Disposition': `inline; filename="${filename}"`,
        },
        body: buf,
      }
    );
    const text = await r.text();
    try { res.status(r.status).json(JSON.parse(text)); }
    catch { res.status(r.status).json({ raw: text }); }
  } catch (e) { res.status(500).json({ error: e.message }); }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Veeqo Sync v4 running on port ${PORT}`));
